
const f=()=>{


try{
    let a =0;
    // console.log(program);
    console.log("program runs succesfully");
    return
}
catch(err){
    console.log("this is an error");

    console.log(p);
}
finally{
    console.log("I am a good boy");
    //close the file
    // exit the loop
    //write ti the log file
}
}

f()
console.log("end");